name: NPM Auth
description: Set up npm authentication
inputs:
  npm-token:
    description: Cache
    required: true
runs:
  using: composite
  steps:
    - run: echo -e "\n//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" >> /tmp/.npmrc
      shell: bash
    - run: echo NPM_CONFIG_USERCONFIG=$(realpath /tmp/.npmrc) >> $GITHUB_ENV
      shell: bash